from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from transformers import T5ForConditionalGeneration, T5Tokenizer
import torch
import os

# ---------- CONFIGURATION ----------
MODEL_PATH = "./model"  # folder containing pytorch_model.bin, config.json, tokenizer files
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ---------- LOAD MODEL & TOKENIZER ----------
print(f"Loading model from {MODEL_PATH} on {DEVICE}...")
try:
    tokenizer = T5Tokenizer.from_pretrained(MODEL_PATH)
    model = T5ForConditionalGeneration.from_pretrained(MODEL_PATH)
    model.to(DEVICE)
    model.eval()
    print("✅ Model loaded successfully")
except Exception as e:
    print(f"❌ Failed to load model: {e}")
    raise

# ---------- FASTAPI APP ----------
app = FastAPI(
    title="T5 Summarizer API",
    description="Summarize long text using a fine-tuned T5 model",
    version="1.0"
)

# Request and response models
class SummarizeRequest(BaseModel):
    text: str = Field(..., min_length=10, example="Your long article text goes here. It should be at least 10 characters.")
    max_length: int = Field(150, ge=20, le=512, description="Maximum summary length in tokens")
    min_length: int = Field(30, ge=10, le=200, description="Minimum summary length in tokens")

class SummarizeResponse(BaseModel):
    summary: str
    input_length: int
    output_length: int

@app.get("/")
def root():
    return {"message": "T5 Summarizer API is running. POST to /summarize"}

@app.post("/summarize", response_model=SummarizeResponse)
async def summarize(request: SummarizeRequest):
    """
    Accepts text and returns a summary generated by the T5 model.
    """
    if not request.text.strip():
        raise HTTPException(status_code=400, detail="Text cannot be empty")

    try:
        # Prepare input with "summarize:" prefix (T5 expects it)
        input_text = "summarize: " + request.text.strip()
        inputs = tokenizer.encode(
            input_text,
            return_tensors="pt",
            truncation=True,
            max_length=1024  # adjust based on your model's max length
        )
        inputs = inputs.to(DEVICE)

        # Generate summary
        summary_ids = model.generate(
            inputs,
            max_length=request.max_length,
            min_length=request.min_length,
            num_beams=4,
            early_stopping=True,
            no_repeat_ngram_size=3
        )
        summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)

        # Return with metadata
        return SummarizeResponse(
            summary=summary,
            input_length=len(request.text),
            output_length=len(summary)
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Summarization failed: {str(e)}")

@app.get("/health")
def health():
    return {"status": "ok", "device": str(DEVICE), "model_loaded": True}

# For running locally (optional, not needed if you use uvicorn command)
# if __name__ == "__main__":
#     import uvicorn
#     uvicorn.run(app, host="0.0.0.0", port=8000)
